version: '3.8'

services:
  fastapi_app:
    build: ./fastapi_app
    env_file:
      - ./fastapi_app/.env
    volumes:
      - storage_volume:/my_project/fastapi_app/storage
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8000:8000
    networks:
      - semyon-network
    command:
      - sh
      - -c
      - |
        alembic -c /my_project/fastapi_app/alembic.ini upgrade head
        uvicorn fastapi_app.src.main:app --reload --host 0.0.0.0 --port 8000

  db:
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.postgres
    ports:
      - 5433:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "storage_db", "-U", "storage_user" ]
    networks:
      - semyon-network

volumes:
  postgres_data:
  storage_volume:
networks:
  semyon-network:
    driver: bridge
