version: '3.8'

services:
  fastapi_app:
    build: ./fastapi_app
    env_file:
      - ./fastapi_app/.env
      - ./fastapi_app/.env.test
      - ./fastapi_app/.env.redis
    depends_on: ["db", "cache"]
    ports:
      - 8000:8000
    networks:
      - semyon-network
    command:
      - sh
      - -c
      - |
        alembic -c /my_project/fastapi_app/alembic.ini upgrade head
        pytest -v /fastapi_app/

  db:
    image: postgres:14.0-alpine
    env_file:
      - ./.env.postgres.test
    ports:
      - 5433:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "storage_db", "-U", "storage_user" ]
    networks:
      - semyon-network

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    networks:
      - semyon-network

networks:
  semyon-network:
    driver: bridge
